server:
  port: 8081
  servlet:
    context-path: /springboot

# 整合mybatis相关配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bootssm?characterEncoding=UTF-8
    username: root
    password: 3.014/*-+
mybatis:
  mapper-locations: classpath:com/weidd/best/springboot_mybatis/mapper/*.xml # 指定mapper配置文件
  type-aliases-package: com.weidd.best.springboot_mybatis.pojo # 指定实体类的包名,默认别名:类名 首字母小写

