
server:
  port: 8081
  servlet:
    context-path: /springboot

# 整合mybatis相关配置
spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bootssm?characterEncoding=UTF-8
    username: root
    password: 3.014/*-+
    # 数据源指定

# mybatis配置
mybatis:
  mapper-locations: classpath:com/weidd/best/springboot_mybatis/mapper/*.xml # 指定mapper配置文件
  type-aliases-package: com.weidd.best.springboot_mybatis.pojo # 指定实体类的包名,默认别名:类名 首字母小写

logging:
  level:
    root: info # 全局(根)的日志 (默认是info) 一般不动
    com.weidd.best.springboot_mybatis.mapper: debug # 输出指定包的日志级别,(可以写多个)
  file:
    name: run222.log # 指定生成日志文件名
    path: ./ # 将日志生成到当前目录(当前项目的目录中)

